### ISSUE TITLE
Error Compile bot

### ISSUE THREAD

**Issue by ruleaker** [hoaan1995/Cosmic-Mirai#11]
[root@localhost ~]# sh build.sh
Compile CnC
Done
Compile bot
BFD: release/stS0ICca: section .init lma 0x80d4 overlaps previous sections
BFD: release/stS0ICca: section .text lma 0x80f0 overlaps previous sections
BFD: release/stS0ICca: section .fini lma 0x1ad0c overlaps previous sections
BFD: release/stS0ICca: section .rodata lma 0x1ad1c overlaps previous sections
BFD: release/stS0ICca: section .ARM.extab lma 0x1b628 overlaps previous sections
BFD: release/stS0ICca: section .ARM.exidx lma 0x1b640 overlaps previous sections
BFD: release/stS0ICca: section `.ARM.exidx' can't be allocated in segment 1
armv7l-strip: release/stS0ICca: Bad value
BFD: release/stS0ICca: section .init lma 0x80d4 overlaps previous sections
BFD: release/stS0ICca: section .text lma 0x80f0 overlaps previous sections
BFD: release/stS0ICca: section .fini lma 0x1ad0c overlaps previous sections
BFD: release/stS0ICca: section .rodata lma 0x1ad1c overlaps previous sections
BFD: release/stS0ICca: section .ARM.extab lma 0x1b628 overlaps previous sections
BFD: release/stS0ICca: section .ARM.exidx lma 0x1b640 overlaps previous sections
BFD: release/stS0ICca: section `.ARM.exidx' can't be allocated in segment 1
armv7l-strip: release/stS0ICca: Bad value
Done
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
/root/dlr/main.c:88:28: error: too many decimal points in number
/root/dlr/main.c: In function 'run':
/root/dlr/main.c:88: error: too few arguments to function 'utils_inet_addr'
armv4l-strip: '/root/dlr/release/dlr.arm': No such file
armv5l-strip: '/root/dlr/release/dlr.arm5': No such file
armv6l-strip: '/root/dlr/release/dlr.arm6': No such file
armv7l-strip: '/root/dlr/release/dlr.arm7': No such file
i586-strip: '/root/dlr/release/dlr.x86': No such file
m68k-strip: '/root/dlr/release/dlr.m68k': No such file
mips-strip: '/root/dlr/release/dlr.mips': No such file
mipsel-strip: '/root/dlr/release/dlr.mpsl': No such file
powerpc-strip: '/root/dlr/release/dlr.ppc': No such file
sh4-strip: '/root/dlr/release/dlr.sh4': No such file
sparc-strip: '/root/dlr/release/dlr.spc': No such file
mv: cannot stat ‘/root/dlr/release/dlr*’: No such file or directory
--2022-06-17 11:45:38--  https://github.com/upx/upx/releases/download/v3.94/upx-3.94-i386_linux.tar.xz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected

![image](https://user-images.githubusercontent.com/67159561/174292509-5f6a05bf-bfb9-4d7f-a485-52e8f09c3020.png)

**Comment by ruleaker** [comment]
oh i got it, bruh,
in the setup file
there is a 
ln -s /usr/lib64/libgmp.so.3  /usr/lib64/libgmp.so.10

it's the other way around

so it should be 
ln -s /usr/lib64/libgmp.so.10  /usr/lib64/libgmp.so.3

lmao

**Comment by ruleaker** [comment]
,no it still not working.......

**Comment by ruleaker** [comment]
my system:

-bash-4.2# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

-bash-4.2# uname -a
Linux localhost.localdomain 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ruleaker** [comment]
Help

**Comment by ruleaker** [comment]
and my mem

-bash-4.2# free
              total        used        free      shared  buff/cache   available
Mem:        8008940      282180     4495188       25340     3231572     7395524
Swap:             0           0           0

**Comment by ruleaker** [comment]
btw
first error


[root@localhost ~]# ln -s /usr/lib64/libgmp.so.3  /usr/lib64/libgmp.so.10
ln: failed to create symbolic link ‘/usr/lib64/libgmp.so.10’: File exists

**Comment by ruleaker** [comment]
hello anybody help?

**Comment by hoaan1995** [comment]
you need to change the IP in the file /dlr/main.c in a way like this

Example: 0,0,0,0

Change , for .

**Comment by ruleaker** [comment]
> 

i've changed it into my server ip using .

**Comment by ruleaker** [comment]
That's probably not the problem,

**Comment by ruleaker** [comment]
![image](https://user-images.githubusercontent.com/67159561/174427314-561c6d3a-a228-497f-80f4-6b9b040ab462.png)
i've already changed it

**Comment by ruleaker** [comment]
oh i got it.......... damn my english is shit

**Comment by ruleaker** [comment]
let me test it
