### ISSUE TITLE
how do i use tcpflood????

### ISSUE THREAD

**Issue by IfinderCodes** [hoaan1995/Cosmic-Mirai#16]

**Comment by Loko415** [comment]
hey bro, do you scan on another server or same server as cnc?

**Comment by IfinderCodes** [comment]
> hey bro, do you scan on another server or same server as cnc?
> 
> 

i did the same server

**Comment by Loko415** [comment]
can u help me on discord Loko#0993

**Comment by Loko415** [comment]
i cant add bots for some reason...

**Comment by JukoiDev** [comment]
cuz yall stupid

**Comment by hoaan1995** [comment]
bruh

**Comment by IfinderCodes** [comment]
ay i found a solution really long time ago i just didn't know i needed a prefix
