### ISSUE TITLE
loader not loading any bots

### ISSUE THREAD

**Issue by IfinderCodes** [hoaan1995/Cosmic-Mirai#6]

**Comment by hoaan1995** [comment]
> _No description provided._

take me picture!

**Comment by IfinderCodes** [comment]
> > _No description provided._
> 
> take me picture!

i cant since i removed it from the server but basically i ran the scanlistener and the loader after changing the ips to the server, i was just staring at the telnet cnc panel and no bots loaded there, i followed every part of the setup guide ran it did the loader and no bots connected to the cnc
