### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by iLaravel** [hoaan1995/Cosmic-Mirai#8]
Idk why but ./loader s
![image](https://user-images.githubusercontent.com/95919109/171030894-d8f0bdc9-d4d7-4ada-973b-e9e474281ea2.png)
aying "Killed" when i wanna load bots into net

**Comment by GamerulEDY** [comment]
is the vps

**Comment by iLaravel** [comment]
fixed

**Comment by ruleaker** [comment]
what

**Comment by ruleaker** [comment]
okey thx man i'll try
